<header class="bg-danger">
    <nav class="container d-flex align-items-center justify-content-between" style="height: 14vh">
        <h3 style="width:40%" class="mb-0">
            <a href="/store" class="nav-link text-light text-left mx-0">Store</a>
        </h3>
    </nav>
</header>
<main class="mt-5 d-flex justify-content-center">
    <section style="width: 360px">
        <form action="/store/auth/login" method="post">
            <input class="form-control mt-3" type="email" name="email" id="email" placeholder="E-mail" />
            <input class="form-control mt-3" type="password" name="password" id="password" placeholder="Senha" />
            <button type="submit" class="btn btn-danger w-100 mt-3">Entrar</button>
            <a href="/store/signup" class="mt-3 nav-link p-0">Ainda não possui cadastro?</a>
        </form>
    </section>
</main>