<header class="bg-danger">
    <nav class="container d-flex align-items-center justify-content-between" style="height: 14vh">
        <h3 style="width:40%" class="mb-0">
            <a href="/store" class="nav-link text-light text-left mx-0">Store</a>
        </h3>
    </nav>
</header>
<main class="mt-5 d-flex justify-content-center">
    <section style="width: 360px">
        <form action="/store/signup/register_user" method="post">
            <input class="form-control mt-3" type="text" name="name" id="name" placeholder="Nome" />
            <input class="form-control mt-3" type="email" name="email" id="email" placeholder="E-mail" />
            <input class="form-control mt-3" type="password" name="password" id="password" placeholder="Senha" />
            <input class="form-control mt-3" type="password" name="confirm-password" id="confirm-password" placeholder="Confirmar senha" />
            <button type="submit" class="btn btn-danger w-100 mt-3">Cadastre-se</button>
            <a href="/store/auth" class="mt-3 nav-link p-0">Já possui cadastro?</a>
        </form>
    </section>
</main>