<header class="bg-danger">
    <nav class="container d-flex align-items-center justify-content-between" style="height: 14vh">
        <h3 style="width:40%" class="mb-0">
            <a href="/store" class="nav-link text-light text-left mx-0">Store</a>
        </h3>
        <?php if (!isset($_SESSION['id'])) { ?>
            <div class="btn-group">
                <button type="button" class="btn btn-danger dropdown-toggle text-left" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Olá, faça seu login <br /> ou cadastre-se
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/store/auth">Entrar</a>
                    <a class="dropdown-item" href="/store/signup">Cadastre-se</a>
                </div>
            </div>
        <?php } else { ?>
            <div class="btn-group">
                <button type="button" class="btn btn-danger dropdown-toggle text-left" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Olá, <?= $_SESSION['name'] ?>
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/store/auth/sign_out">Sair</a>
                </div>
            </div>
        <?php } ?>
    </nav>
</header>

<main class="container">
    <div id="carouselExampleIndicators" class="carousel slide mt-5" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
            <img width="100%" src="https://images-americanas.b2w.io/spacey/acom/2021/01/15/home_destaque-desk_volta-as-aulas_cupom.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
            <img width="100%" src="https://images-americanas.b2w.io/spacey/acom/2021/01/19/Destaque-seguros_evento-conectados.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
            <img width="100%" src="https://images-americanas.b2w.io/spacey/acom/2021/01/15/139395631_402782077469968_5416262812003784455_n.png" class="d-block w-100" alt="...">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <section class="row mt-5">
        <article class="col-md-4">
            <img width="100%" src="https://images-americanas.b2w.io/spacey/acom/2021/01/19/DESK-TRIPLO-TECH20.01.png" alt="">
        </article>
        <article class="col-md-4">
            <img width="100%" src="https://images-americanas.b2w.io/spacey/acom/2021/01/19/DESK-TRIPLO-VERAO20.01.png" alt="">
        </article>
        <article class="col-md-4">
            <img width="100%" src="https://images-americanas.b2w.io/spacey/acom/2021/01/19/DESK-TRIPLO-SECRETA20.01.png" alt="">
        </article>
    </section>
</main>